on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '17'
      - run: ./mvnw verify
