on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5
      - run: mvn verify
